server:
  port: 9000

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: demo

  datasource:
    platform: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://ollangdb.ctcjffdec249.ap-northeast-2.rds.amazonaws.com:3306/ollangdb
    username: master
    password: ollang999
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
#     driver-class-name: com.mysql.jdbc.Driver # mysql 5버전